name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  id-token: write

jobs:
  # unit tests
  # units:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3.1.0
  #   - run: npm ci
  #   - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
    - name: Authenticate with Google Cloud
      id: auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: projects/22448147000/locations/global/workloadIdentityPools/ci-pool/providers/github
        service_account: gha-select-qa-env@moonswitch-dev.iam.gserviceaccount.com
    - uses: ./
      id: select-qa-env
      with:
        cloud_provider: gcp
        table: qa-envs
    - name: Check Output
      run: echo "The url for the selected QA environment is ${{ steps.select-qa-env.outputs.url }}"
